# ----- BUILD -----
    FROM node:20 AS builder

    WORKDIR /app
    COPY package*.json ./
    RUN npm install -g typescript

    RUN npm install
    
    COPY . .
    RUN npm run build
    
    # ----- PRODUCTION -----
    FROM node:20-slim
    
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install --omit=dev
    
    COPY --from=builder /app/dist ./dist
    
    EXPOSE 3000
    CMD ["node", "dist/main.js"]
    